import { type NextPage } from 'next'
import Head from 'next/head'
import Hero from '../scenes/hero'
import ContactUs from '../scenes/contactUs'
import About from '../scenes/about'
import TrainingOptions from '../scenes/trainingOptions'
import CalendarComponent from '@components/Calendar'
import { formatISO } from 'date-fns'
import { prisma } from '../server/db/client'
import { type Day } from '@prisma/client'
import { SelectedPage } from '../shared/types'
import Header from 'src/scenes/header'
import { useState, useEffect } from 'react'

type HomeProps = {
  days: Day[]
  closedDays: string[] // as ISO String
}

const Home: NextPage<HomeProps> = ({ days, closedDays }) => {
  const [selectedPage, setSelectedPage] = useState<SelectedPage>(SelectedPage.Hero)
  const [isTopOfPage, setIsTopOfPage] = useState<boolean>(true)

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY === 0) {
        setIsTopOfPage(true)
        setSelectedPage(SelectedPage.Hero)
      }
      if (window.scrollY !== 0) setIsTopOfPage(false)
    }
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  return (
    <>
      <Head>
        <title>Booking</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header
        isTopOfPage={isTopOfPage}
        selectedPage={selectedPage}
        setSelectedPage={setSelectedPage}
      />

      <main className='var(--centeredTop)'>
        <Hero setSelectedPage={setSelectedPage} />
        <TrainingOptions setSelectedPage={setSelectedPage} />
        <About setSelectedPage={setSelectedPage} />
        <CalendarComponent days={days} closedDays={closedDays} />
        <ContactUs setSelectedPage={setSelectedPage} />
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const days = await prisma.day.findMany()
  const closedDays = (await prisma.closedDay.findMany())?.map((day) => formatISO(day.date))
  return { props: { days, closedDays } }
}

export default Home
