import { NextPage } from 'next'
import Head from 'next/head'

interface HeaderProps {
  heading: string
}

const header: NextPage<HeaderProps> = ({ heading }) => {
  return (
    <Head>
      <title>{heading}</title>
      <meta
        name='description'
        content='Generated by create next app'
      />
      <link
        rel='icon'
        href='/favicon.ico'
      />
    </Head>
  )
}

export default header
